### ISSUE TITLE
Question - why not use the GTranslate nuget?

### ISSUE THREAD

**Issue by stevencohn** [David-Maisonave/ABetterTranslator#3]
You're pulling in the GTranslate source code as a project in the solution. Why not use the nuget package?

**Comment by David-Maisonave** [comment]
The version I'm using has many changes.
* 19 additional languages.
* Removed alias logic which was causing issues, and it was not helping at all with this project.
* Minor fixes associated with compiler warnings.
* Renamed some of the languages, because they were not the name used in [ISO 639-1](https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes)
* Sorted the language list in LanguageDictionary.cs so as to make it easier to catch duplicate entries.
  * Ironically, the only duplicate I found was one which I added by mistake.
* Added Tagalog which is the correct name for the spoken language in the Philippines.  Filipino is a slang.  I still left Filipino in the list because I've seen major companies like Microsoft, using the slang name.

When time permits, I'll see if I can add the changes to the main [GTranslate](https://github.com/d4n3436/GTranslate) library, but I doubt if the owner will take all the changes.
